# docker-compose.yml
version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app

  app_nginx:
    build:
      context: ./docker/app_nginx
    depends_on:
      - app
    ports:
      - "8888:80"

  front_nginx:
    image: nginx:stable
    ports:
      - "8777:80"
    volumes:
      - ./public:/usr/share/nginx/html

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8777
        allow_anonymous true
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

###> symfony/mercure-bundle ###
volumes:
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
